USE intranet_db;

INSERT INTO funcionarios (re, nome, cargo, departamento, email, ramal, status, created_by)
VALUES
('26', 'Adolfo Oldemburgo', 'Gerente de Tecnologia, inovação e infraestrutura', 'Diretoria de Operações', 'adolfo.oldemburgo@iluminacao.net.br', '2778', 'ativo', NULL),
('4', 'Anderson Vido', 'Coordenador de Segurança do Trabalho', 'Gestão de Pessoas', 'anderson.vido@iluminacao.net.br', '2774', 'ativo', NULL),
('5', 'Agnaldo Pereira de Oliveira', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('6', 'Antonio Ferreira Neto', 'Assistente Operacional', 'Gestão de Estoque e Suprimentos', 'antonio.neto@iluminacao.net.br', '2779', 'ativo', NULL),
('168', 'Artur Adolfo Falkovski', 'Engenheiro Eletricista', 'Planejamento e Projetos', 'artur.falkovski@iluminacao.net.br', '2794', 'ativo', NULL),
('73', 'Augusto Cesar de Campos Soares', 'Coordenador De Drones', 'Planejamento e Projetos', 'augusto.soares@iluminacao.net.br', '2754', 'ativo', NULL),
('218', 'Beatriz Borges da Silva', 'Estagiária', 'Gestão de Estoque e Suprimentos', 'beatriz.silva@iluminacao.net.br', '2784', 'ativo', NULL),
('209', 'Camila Aguiar da Cruz', 'Estagiária', 'Gestão de Licitações e Contratos', 'camila.cruz@iluminacao.net.br', '2795', 'ativo', NULL),
('96', 'Cezar Pereira dos Santos', 'Auditor Interno', 'Contabilidade', 'cezar.santos@iluminacao.net.br', '2762', 'ativo', NULL),
('44', 'Daniele Aparecida dos Santos', 'Gerente Financeira', 'Financeiro', 'daniele.santos@iluminacao.net.br', '2758', 'ativo', NULL),
('80', 'Debora Alves Inumaru', 'Gerente de Licitações e Contratos', 'Gestão de Licitações e Contratos', 'debora.inumaru@iluminacao.net.br', '2757', 'ativo', NULL),
('194', 'Denise Martins do Amaral Silva', 'Estagiária', 'Contabilidade', 'denise.silva@iluminacao.net.br', '2760', 'ativo', NULL),
('197', 'Diego Pereira da Costa Prazeres', 'Assessor de Diretoria e Presidência', 'Presidência', 'diego.prazeres@iluminacao.net.br', '2764', 'ativo', NULL),
('8', 'Edson Alves da Silva Junior', 'Coordenador de Serralheria', 'Operações', 'edson.junior@iluminacao.net.br', '2767', 'ativo', NULL),
('191', 'Eduardo Stoeberl Bertolla Sandi', 'Estagiário', 'Planejamento e Projetos', 'eduardo.sandi@iluminacao.net.br', '2796', 'ativo', NULL),
('9', 'Elias Pacheco de Andrade', 'Coordenador de Operações', 'Operações', 'elias.andrade@iluminacao.net.br', '2772', 'ativo', NULL),
('10', 'Elizeu dos Santos Junior', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('205', 'Erica Cristina Pega de Oliveira', 'Agente de Contratação/Pregoeiro', 'Gestão de Licitações e Contratos', 'erica.oliveira@iluminacao.net.br', '2769', 'ativo', NULL),
('11', 'Fabio Moraes Caetano', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('60', 'Fernando Martins', 'Agente Eletricista', 'Operações', 'fernando.martins@iluminacao.net.br', '2771', 'ativo', NULL),
('106', 'Fernando Rodrigues da Cruz', 'Coordenador de Pesquisa e Desenvolvimento', 'Gestão de Tecnologia, Inovação e Infraestrutura', 'fernando.cruz@iluminacao.net.br', '2777', 'ativo', NULL),
('13', 'Filipe Alves Gil', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('196', 'Gabriel Fernando Pereira Carneiro', 'Aprendiz', 'Gestão de Licitações e Contratos', 'gabriel.carneiro@iluminacao.net.br', '2776', 'ativo', NULL),
('27', 'Guilherme Akio Hayasaka', 'Responsável Tec Engenharia', 'Operações', 'guilherme.hayasaka@iluminacao.net.br', '2773', 'ativo', NULL),
('14', 'Guilherme dos Santos Costa', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('219', 'Guilherme Meranca D''Avila', 'Estagiário', 'Gestão de Estoque e Suprimentos', 'guilherme.meranca@iluminacao.net.br', NULL, 'ativo', NULL),
('213', 'Gustavo Felix de Jesus', 'Jovem Aprendiz', 'Gestão de Pessoas', 'gustavo.jesus@iluminacao.net.br', '2770', 'ativo', NULL),
('202', 'Gustavo Oliveira Leme', 'Assessor de Diretoria e Presidência', 'Presidência', 'gustavo.leme@iluminacao.net.br', '2789', 'ativo', NULL),
('28', 'Helder Rafael Cavalcante de Oliveira', 'Gerente de Operações', 'Operações', 'helder.oliveira@iluminacao.net.br', '2771', 'ativo', NULL),
('206', 'Henrique Hiroshi Kikuchi', 'Agente Adm e Financeiro', 'Operações', 'henrique.kikuchi@iluminacao.net.br', '2797', 'ativo', NULL),
('43', 'Hercilia Setsuko Kajimoto', 'Técnica Contábil', 'Gestão de Pessoas', 'hercilia.kajimoto@iluminacao.net.br', '2759', 'ativo', NULL),
('94', 'Jhonatan Luis Nunes', 'Gerente de Contabilidade', 'Contabilidade', 'jhonatan.nunes@iluminacao.net.br', '2780', 'ativo', NULL),
('16', 'João Gabriel Germanovix de Sousa Ferreira', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('178', 'João Victor Pedrosa Marcolini', 'Agente Adm e Financeiro', 'Gestão de Estoque e Suprimentos', 'joao.marcolini@iluminacao.net.br', '2785', 'ativo', NULL),
('217', 'Jonatan Guttler Freitas', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('29', 'José Milton Puga Neto', 'Téc Eletrotécnico', 'Operações', 'jose.neto@iluminacao.net.br', '2765', 'ativo', NULL),
('211', 'Kamila Fernanda dos Santos Souza', 'Estagiária', 'Contabilidade', 'kamila.souza@iluminacao.net.br', '2791', 'ativo', NULL),
('35', 'Karen Larissa Santos Balarin Ambrosio', 'Coordenadora de Licitações e Contratos', 'Gestão de Licitações e Contratos', 'karen.balarin@iluminacao.net.br', '2755', 'ativo', NULL),
('215', 'Lenise Dallmann Haber', 'Agente Adm e Financeiro', 'Gestão de Licitações e Contratos', 'lenise.haber@iluminacao.net.br', '2793', 'ativo', NULL),
('192', 'Leonilda Aparecida Piras Goulart Der Bedrossian', 'Assessora de Diretoria e Presidência', 'Gestão de Licitações e Contratos', 'leonilda.bedrossian@iluminacao.net.br', '2792', 'ativo', NULL),
('19', 'Luciano Aparecido dos Santos', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('59', 'Luiz Carlos Biz', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('111', 'Luiz Henrique Pistori', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('110', 'Luiz Henrique Tamos de Carvalho', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('57', 'Maicon Martins de Oliveira', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('33', 'Marcela de Oliveira Ribeiro', 'Gerente de Planejamento e Projetos', 'Planejamento e Projetos', 'marcela.ribeiro@iluminacao.net.br', '2751', 'ativo', NULL),
('109', 'Marcelo Neves Alda', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('92', 'Marcelo Willians Tomaz', 'Assist. Operacional', 'Operações', 'marcelo.tomaz@iluminacao.net.br', '2767', 'ativo', NULL),
('118', 'Marcia Suemi Utiyama', 'Agente Adm e Financeiro', 'Gestão de Estoque e Suprimentos', 'marcia.utiyama@iluminacao.net.br', '2766', 'ativo', NULL),
('20', 'Marcos Antonio Bottine', 'Coordenador de Operações', 'Operações', 'marcos.bottine@iluminacao.net.br', '2761', 'ativo', NULL),
('214', 'Maria Gabriela Stasiak de Freitas', 'Aprendiz', 'Gestão de Estoque e Suprimentos', 'maria.freitas@iluminacao.net.br', '2784', 'ativo', NULL),
('199', 'Miriam Melo de Campos', 'Agente Adm e Financeiro', 'Gestão de Estoque e Suprimentos', 'miriam.campos@iluminacao.net.br', '2782', 'ativo', NULL),
('169', 'Nara Hitomi Lodi Daikuhara', 'Assistente Operacional', 'Governança Corporativa', 'nara.daikuhara@iluminacao.net.br', '2753', 'ativo', NULL),
('221', 'Nelson De Melo Teixeira Junior', 'Técnico de TI', 'Gerência de Tecnologia, inovação e infraestrutura', 'nelson.junior@iluminacao.net.br', '2799', 'ativo', NULL),
('207', 'Paulo Arcoverde Nascimento', 'Assessor de Diretoria e Presidência', 'Presidência', 'paulo.arcoverde@iluminacao.net.br', '2768', 'ativo', NULL),
('198', 'Paulo Sergio Moura', 'Diretor Adm e Financeiro', 'Diretoria ADM Financeira', 'paulo.moura@iluminacao.net.br', '2788', 'ativo', NULL),
('107', 'Roberto Marcelino Lopes', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('58', 'Robson Weslley de Oliveira', 'Assist. Lab. Iluminação Públic', 'Operações', 'robson.oliveira@iluminacao.net.br', '2787', 'ativo', NULL),
('177', 'Taynara Ribeiro Eleutério', 'Agente de Contratação/Pregoeiro', 'Gestão de Licitações e Contratos', 'taynara.eleuterio@iluminacao.net.br', '2783', 'ativo', NULL),
('91', 'Thiago Dantas Carballal', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('23', 'Tiago Antunes Ferreira', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('24', 'Uandre Vicente de Medeiros', 'Assistente Operacional', 'Gerência de Tecnologia, inovação e infraestrutura', 'uandre.medeiros@iluminacao.net.br', '2763', 'ativo', NULL),
('200', 'Vitor Daniel Genovez Horita', 'Diretor de Operações', 'Diretoria de Operações', 'vitor.horita@iluminacao.net.br', '2790', 'ativo', NULL),
('193', 'Wagner Seiki Oguido', 'Agente de Contratação/Pregoeiro', 'Gestão de Licitações e Contratos', 'wagner.oguido@iluminacao.net.br', '2775', 'ativo', NULL),
('25', 'Wagner Yoshihito Nishi', 'Coordenador de Operações', 'Operações', 'wagner.nishi@iluminacao.net.br', '2752', 'ativo', NULL),
('108', 'Weslley Santos Barbosa', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('90', 'Yuri Val Jordao Gomes', 'Agente Eletricista', 'Operações', '', '2771', 'ativo', NULL),
('95', 'Zenobio Sales Pinheiro Junior', 'Gerente de Estoque e Suprimentos', 'Gestão de Estoque e Suprimentos', 'zenobio.pinheiro@iluminacao.net.br', '2781', 'ativo', NULL);

UPDATE funcionarios
SET status = 'inativo'
WHERE re IN ('38', '195');
