-- Crear banco de dados
CREATE DATABASE IF NOT EXISTS intranet_db;
USE intranet_db;

-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  role VARCHAR(50) DEFAULT 'viewer',
  birth_date DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela de chamados
CREATE TABLE IF NOT EXISTS chamados (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  ticket_number VARCHAR(30) UNIQUE NULL,
  requester_name VARCHAR(100),
  department VARCHAR(100),
  unit_name VARCHAR(100),
  opening_channel VARCHAR(30) DEFAULT 'sistema',
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(50) DEFAULT 'normal',
  impact VARCHAR(50) DEFAULT 'individual',
  urgency VARCHAR(50) DEFAULT 'media',
  support_level VARCHAR(10) DEFAULT 'N1',
  category VARCHAR(100),
  subcategory VARCHAR(100),
  status VARCHAR(50) DEFAULT 'aberto',
  assigned_to INT,
  resolved_by INT,
  attendance_type VARCHAR(30),
  first_response_due_at DATETIME NULL,
  first_response_at DATETIME NULL,
  service_started_at DATETIME NULL,
  resolution_due_at DATETIME NULL,
  resolved_at DATETIME NULL,
  opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME NULL,
  sla_paused_at DATETIME NULL,
  sla_pause_reason VARCHAR(500),
  waiting_user_seconds INT DEFAULT 0,
  waiting_vendor_seconds INT DEFAULT 0,
  paused_seconds INT DEFAULT 0,
  sla_first_response_met TINYINT(1) NULL,
  sla_resolution_met TINYINT(1) NULL,
  root_cause VARCHAR(500),
  action_taken TEXT,
  solution_applied TEXT,
  solution_type VARCHAR(30),
  needs_return TINYINT(1) DEFAULT 0,
  part_replaced TINYINT(1) DEFAULT 0,
  external_service TINYINT(1) DEFAULT 0,
  final_status VARCHAR(50),
  closure_notes TEXT,
  user_validation_status VARCHAR(30) DEFAULT 'nao_enviado',
  user_validation_comment VARCHAR(500),
  user_validated_at DATETIME NULL,
  satisfaction_level VARCHAR(40),
  satisfaction_score TINYINT NULL,
  satisfaction_comment VARCHAR(500),
  recurrence_flag TINYINT(1) DEFAULT 0,
  recurrence_type VARCHAR(100),
  reopen_count INT DEFAULT 0,
  last_reopen_reason VARCHAR(500),
  asset_tag VARCHAR(100),
  serial_number VARCHAR(100),
  hostname VARCHAR(100),
  ip_address VARCHAR(45),
  extension_number VARCHAR(30),
  affected_system VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_user_id (user_id),
  INDEX idx_status (status),
  INDEX idx_ticket_number (ticket_number),
  INDEX idx_chamados_category (category),
  INDEX idx_chamados_subcategory (subcategory),
  INDEX idx_chamados_opened_at (opened_at),
  INDEX idx_chamados_department (department),
  INDEX idx_chamados_assigned_to (assigned_to)
);

-- Tabela de anexos de chamados
CREATE TABLE IF NOT EXISTS chamado_attachments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chamado_id INT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(100),
  file_size INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chamado_id) REFERENCES chamados(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chamado_historico (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chamado_id INT NOT NULL,
  changed_by INT NULL,
  action_type VARCHAR(50) NOT NULL,
  field_name VARCHAR(100) NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  from_status VARCHAR(50) NULL,
  to_status VARCHAR(50) NULL,
  observation VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chamado_id) REFERENCES chamados(id) ON DELETE CASCADE,
  FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_chamado_historico_chamado_id (chamado_id),
  INDEX idx_chamado_historico_created_at (created_at)
);

-- Tabelas de chamados de infraestrutura
CREATE TABLE IF NOT EXISTS infra_chamados (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  ticket_number VARCHAR(30) UNIQUE NULL,
  requester_name VARCHAR(100),
  department VARCHAR(100),
  unit_name VARCHAR(100),
  opening_channel VARCHAR(30) DEFAULT 'sistema',
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(50) DEFAULT 'media',
  impact VARCHAR(50) DEFAULT 'individual',
  urgency VARCHAR(50) DEFAULT 'media',
  support_level VARCHAR(10) DEFAULT 'N1',
  category VARCHAR(100),
  subcategory VARCHAR(100),
  status VARCHAR(50) DEFAULT 'aberto',
  assigned_to INT NULL,
  resolved_by INT NULL,
  attendance_type VARCHAR(30) NULL,
  first_response_due_at DATETIME NULL,
  first_response_at DATETIME NULL,
  service_started_at DATETIME NULL,
  resolution_due_at DATETIME NULL,
  resolved_at DATETIME NULL,
  opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME NULL,
  sla_paused_at DATETIME NULL,
  sla_pause_reason VARCHAR(500) NULL,
  environment VARCHAR(120) NULL,
  asset_identifier VARCHAR(120) NULL,
  safety_risk TINYINT(1) NOT NULL DEFAULT 0,
  activity_interrupted TINYINT(1) NOT NULL DEFAULT 0,
  needs_approval TINYINT(1) NOT NULL DEFAULT 0,
  approval_granted TINYINT(1) NULL,
  requires_vendor TINYINT(1) NOT NULL DEFAULT 0,
  material_needed TINYINT(1) NOT NULL DEFAULT 0,
  material_description VARCHAR(500) NULL,
  desired_date DATE NULL,
  estimated_cost DECIMAL(12,2) NULL,
  actual_cost DECIMAL(12,2) NULL,
  supplier_name VARCHAR(120) NULL,
  waiting_user_seconds INT NOT NULL DEFAULT 0,
  waiting_vendor_seconds INT NOT NULL DEFAULT 0,
  paused_seconds INT NOT NULL DEFAULT 0,
  sla_first_response_met TINYINT(1) NULL,
  sla_resolution_met TINYINT(1) NULL,
  root_cause VARCHAR(500) NULL,
  action_taken TEXT NULL,
  solution_applied TEXT NULL,
  final_status VARCHAR(50) NULL,
  closure_notes TEXT NULL,
  user_validation_status VARCHAR(30) NOT NULL DEFAULT 'nao_enviado',
  user_validation_comment VARCHAR(500) NULL,
  user_validated_at DATETIME NULL,
  recurrence_flag TINYINT(1) NOT NULL DEFAULT 0,
  recurrence_type VARCHAR(100) NULL,
  reopen_count INT NOT NULL DEFAULT 0,
  last_reopen_reason VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_infra_user_id (user_id),
  INDEX idx_infra_status (status),
  INDEX idx_infra_ticket_number (ticket_number),
  INDEX idx_infra_category (category),
  INDEX idx_infra_subcategory (subcategory),
  INDEX idx_infra_opened_at (opened_at),
  INDEX idx_infra_department (department),
  INDEX idx_infra_assigned_to (assigned_to)
);

CREATE TABLE IF NOT EXISTS infra_attachments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chamado_id INT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(100),
  file_size INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chamado_id) REFERENCES infra_chamados(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS infra_historico (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chamado_id INT NOT NULL,
  changed_by INT NULL,
  action_type VARCHAR(50) NOT NULL,
  field_name VARCHAR(100) NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  from_status VARCHAR(50) NULL,
  to_status VARCHAR(50) NULL,
  observation VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chamado_id) REFERENCES infra_chamados(id) ON DELETE CASCADE,
  FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_infra_historico_chamado_id (chamado_id),
  INDEX idx_infra_historico_created_at (created_at)
);

-- Controle de frota
CREATE TABLE IF NOT EXISTS frota_veiculos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  placa VARCHAR(10) NOT NULL UNIQUE,
  prefixo VARCHAR(50),
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  ano_fabricacao INT,
  ano_modelo INT,
  tipo_veiculo VARCHAR(100) NOT NULL,
  categoria VARCHAR(100),
  renavam VARCHAR(50),
  chassi VARCHAR(100),
  cor VARCHAR(50),
  combustivel VARCHAR(50),
  setor_responsavel VARCHAR(100),
  motorista_responsavel VARCHAR(120),
  unidade VARCHAR(100),
  status_operacional VARCHAR(50) NOT NULL DEFAULT 'disponivel',
  quilometragem_atual INT NOT NULL DEFAULT 0,
  data_ultima_revisao DATE,
  km_ultima_revisao INT,
  data_proxima_revisao DATE,
  km_proxima_revisao INT,
  vencimento_licenciamento DATE,
  vencimento_seguro DATE,
  vencimento_extintor DATE,
  observacoes TEXT,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_frota_veiculos_status (status_operacional),
  INDEX idx_frota_veiculos_ativo (ativo)
);

CREATE TABLE IF NOT EXISTS frota_chamados (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  ticket_number VARCHAR(30) UNIQUE,
  requester_name VARCHAR(100),
  department VARCHAR(100) NOT NULL,
  unit_name VARCHAR(100) NOT NULL,
  title VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  vehicle_id INT NOT NULL,
  request_type VARCHAR(100) NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'media',
  status VARCHAR(50) NOT NULL DEFAULT 'aberto',
  assigned_to INT,
  resolved_by INT,
  current_mileage INT NOT NULL DEFAULT 0,
  driver_name VARCHAR(120),
  vehicle_location VARCHAR(255),
  vehicle_in_operation TINYINT(1) NOT NULL DEFAULT 1,
  safety_risk TINYINT(1) NOT NULL DEFAULT 0,
  needs_tow TINYINT(1) NOT NULL DEFAULT 0,
  activity_interrupted TINYINT(1) NOT NULL DEFAULT 0,
  vehicle_unavailable TINYINT(1) NOT NULL DEFAULT 0,
  supplier_name VARCHAR(120),
  supplier_contacted_at DATETIME,
  expected_return_at DATETIME,
  estimated_cost DECIMAL(12,2),
  approved_cost DECIMAL(12,2),
  actual_cost DECIMAL(12,2),
  quote_number VARCHAR(80),
  invoice_number VARCHAR(80),
  diagnosis TEXT,
  action_taken TEXT,
  parts_used TEXT,
  service_performed TEXT,
  solution TEXT,
  internal_notes TEXT,
  return_date DATETIME,
  opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  first_response_due_at DATETIME,
  first_response_at DATETIME,
  service_started_at DATETIME,
  resolution_due_at DATETIME,
  resolved_at DATETIME,
  closed_at DATETIME,
  sla_paused_at DATETIME,
  sla_pause_reason VARCHAR(500),
  paused_seconds INT NOT NULL DEFAULT 0,
  sla_first_response_met TINYINT(1),
  sla_resolution_met TINYINT(1),
  final_status VARCHAR(50),
  user_validation_status VARCHAR(30) NOT NULL DEFAULT 'nao_enviado',
  user_validation_comment VARCHAR(500),
  user_validated_at DATETIME,
  reopen_count INT NOT NULL DEFAULT 0,
  last_reopen_reason VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (vehicle_id) REFERENCES frota_veiculos(id),
  FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_frota_chamados_user (user_id),
  INDEX idx_frota_chamados_status (status),
  INDEX idx_frota_chamados_vehicle (vehicle_id),
  INDEX idx_frota_chamados_opened (opened_at),
  INDEX idx_frota_chamados_assigned (assigned_to)
);

CREATE TABLE IF NOT EXISTS frota_attachments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chamado_id INT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(100),
  file_size INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chamado_id) REFERENCES frota_chamados(id) ON DELETE CASCADE,
  INDEX idx_frota_attachments_chamado (chamado_id)
);

CREATE TABLE IF NOT EXISTS frota_historico (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chamado_id INT NOT NULL,
  changed_by INT,
  action_type VARCHAR(50) NOT NULL,
  field_name VARCHAR(100),
  old_value TEXT,
  new_value TEXT,
  from_status VARCHAR(50),
  to_status VARCHAR(50),
  observation VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chamado_id) REFERENCES frota_chamados(id) ON DELETE CASCADE,
  FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_frota_historico_chamado (chamado_id),
  INDEX idx_frota_historico_created (created_at)
);

CREATE TABLE IF NOT EXISTS frota_indisponibilidades (
  id INT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id INT NOT NULL,
  chamado_id INT,
  data_inicio DATETIME NOT NULL,
  data_fim DATETIME,
  motivo TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'aberta',
  responsavel INT,
  observacao TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vehicle_id) REFERENCES frota_veiculos(id),
  FOREIGN KEY (chamado_id) REFERENCES frota_chamados(id) ON DELETE SET NULL,
  FOREIGN KEY (responsavel) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_frota_indisponibilidade_vehicle (vehicle_id),
  INDEX idx_frota_indisponibilidade_open (data_fim)
);

-- Tabela de comunicados
CREATE TABLE IF NOT EXISTS comunicados (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  priority VARCHAR(50) DEFAULT 'normal',
  announcement_type VARCHAR(50) NOT NULL DEFAULT 'manual',
  generated_key VARCHAR(100) UNIQUE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_created_at (created_at)
);

-- Tabela de documentos
CREATE TABLE IF NOT EXISTS documentos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(100),
  description TEXT,
  file_path VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100),
  file_size INT,
  downloads INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_category (category),
  INDEX idx_created_at (created_at)
);

-- Tabela de funcionários
CREATE TABLE IF NOT EXISTS funcionarios (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL,
  re VARCHAR(20),
  cargo VARCHAR(100) NOT NULL,
  ramal VARCHAR(20),
  email VARCHAR(100) NOT NULL,
  foto_path VARCHAR(500),
  foto_name VARCHAR(255),
  foto_size INT,
  departamento VARCHAR(100),
  status VARCHAR(50) DEFAULT 'ativo',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by INT,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_status (status),
  INDEX idx_cargo (cargo),
  INDEX idx_created_at (created_at)
);

-- Tabela de banco de ideias
CREATE TABLE IF NOT EXISTS ideias (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  titulo VARCHAR(150) NOT NULL,
  descricao TEXT NOT NULL,
  categoria VARCHAR(100),
  status VARCHAR(50) DEFAULT 'nova',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_ideias_user_id (user_id),
  INDEX idx_ideias_status (status),
  INDEX idx_ideias_created_at (created_at)
);

-- Inserir usuário admin padrão (senha: admin123)
INSERT INTO users (username, email, password, name, department, role) 
VALUES ('admin', 'admin@intranet.com', '$2a$10$eImiTXuWVxfaHNYY0iDH2OPST9/PgBkqquzi.Ss7KIUgO2t0jWMUe', 'Administrador', 'TI', 'admin');
